In [46]:
import lime
import sklearn
import numpy as np
import sklearn
import sklearn.ensemble
import sklearn.metrics
from __future__ import print_function
import pandas as pd

In [47]:
credit_df = pd.read_csv('german_credit_data_preprocessed.csv')
credit_df.head()
credit_df = credit_df.select_dtypes(exclude=['object'])

In [48]:
X = credit_df.iloc[:, :-1].values
y = credit_df.iloc[:,-1].values

In [49]:
X

array([[   0,    6, 1169, ...,   67,    2,    1],
       [   1,   48, 5951, ...,   22,    1,    1],
       [   2,   12, 2096, ...,   49,    1,    2],
       ...,
       [ 997,   12,  804, ...,   38,    1,    1],
       [ 998,   45, 1845, ...,   23,    1,    1],
       [ 999,   45, 4576, ...,   27,    1,    1]], dtype=int64)

In [50]:
type(X)

numpy.ndarray

In [51]:
y

array([1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2,
       1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1,

In [52]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, train_size=0.80)

In [53]:
rfc = sklearn.ensemble.RandomForestClassifier(n_estimators=500)
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500)

In [54]:
sklearn.metrics.accuracy_score(y_test, rfc.predict(X_test))

0.71

## Using LIME

In [55]:
from lime import lime_text
from sklearn.pipeline import make_pipeline
c = make_pipeline(rfc)

In [56]:
X_test

array([[ 603,   36, 3349, ...,   28,    1,    1],
       [ 136,   27, 8613, ...,   27,    2,    1],
       [ 629,    9, 3832, ...,   64,    1,    1],
       ...,
       [ 254,    9, 2030, ...,   24,    1,    1],
       [  50,   24, 2333, ...,   29,    1,    1],
       [ 771,   36, 8065, ...,   25,    2,    1]], dtype=int64)

In [58]:
print(c.predict_proba([X_test[0]]))

[[0.488 0.512]]


In [37]:
from lime.lime_text import LimeTextExplainer
class_names = ['good_customer', 'bad_customer']
explainer = LimeTextExplainer(class_names=class_names)

In [70]:
idx = 6
print(X_test[idx])
exp = explainer.explain_instance(X_test[idx], rfc.predict_proba, num_features=3)
print('Document id: %d' % idx)
print('Probability(christian) =', rfc.predict_proba([X_test[idx]])[0,1])
print('True class: %s' % class_names[y_test[idx]])

[ 788   48 6224    4    4   50    1    1]


TypeError: cannot use a string pattern on a bytes-like object

## 3 Write down your insights

1 <b>Were the explanations helpful to you?</b>
Not clearly, as explainer was giving error message.

2 <b>Do you think that LIME helps you better understand the model's behaviors?</b>
To some extent from the Lime tutorial notebook, it shows the features which are impacting and which side.

3 <b>Are you more confident in the model than before?</b>
Its really hard to say based on one dataset.



## 4 What is the gist of the model's prediction behavior? What is your understanding of it and how would you explain it to a non-expert?

From the lime tutorial, predictions was getting same if the instance has the same feature. It is relatively easy to explain to non-expert with the visualization rather then the showing the model parameter table.